# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-11 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('risk_status', models.CharField(choices=[(b'Hi', b'High'), (b'Med', b'Medium'), (b'Lo', b'Low')], default=b'Med', max_length=2)),
                ('cash_amount', models.FloatField(default=0)),
                ('sector_breakdown', models.CharField(max_length=100)),
            ],
        ),
    ]
