# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-11 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_stocks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stocks',
        ),
    ]
