# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-11 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='id',
        ),
        migrations.AddField(
            model_name='choice',
            name='symbol',
            field=models.CharField(default=b'AAA', max_length=5, primary_key=True, serialize=False),
        ),
    ]
