# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190211_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0)),
                ('transaction_type', models.CharField(choices=[(b'+', b'Buy'), (b'-', b'Sell')], default=b'+', max_length=2)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Stocks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Users')),
            ],
        ),
    ]
