# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190314_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='amount',
            new_name='number_of_shares',
        ),
    ]
