# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190321_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='sector_breakdown',
        ),
        migrations.AlterField(
            model_name='users',
            name='risk_status',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
