# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190328_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shares',
            name='cash_amount',
        ),
        migrations.RemoveField(
            model_name='shares',
            name='risk_status',
        ),
        migrations.AddField(
            model_name='users',
            name='sector_breakdown',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='risk_status',
            field=models.CharField(choices=[(b'Hi', b'High'), (b'Med', b'Medium'), (b'Lo', b'Low')], default=b'Med', max_length=2),
        ),
    ]
