# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190328_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='cash_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shares',
            name='risk_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='risk_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
